/* Auto-generated by tools/sync_symbols.py — do not edit.
 * Source: symbols.toml (Spider-Man 2: Enter Electro)
 * Progressive symbols: discover → label → manipulate via PSX_FN_*.
 */
#pragma once

/* guessed: SYSTEM.CNF / EXE entry PC (probe seed) */
#define PSX_FN_BootEntry 0x80093C68u
#define func_80093C68 BootEntry  /* alias */
